### PR TITLE
Fixes translation artifact with 'Show Archived' filter from previous fix

### PR DESCRIPTION
**Pull request by amanji**

### CODE REVIEW

**Review by swcurran — APPROVED** [review]
LGTM

**Comment by swcurran** [comment]
@amanji -- please push on getting this promoted to prod.

**Comment by swcurran** [comment]
@WadeBarnes -- looks good on Test.  Verified.

**Comment by WadeBarnes** [comment]
Release cut and deployed to `prod`; https://github.com/bcgov/orgbook-bc-client/releases/tag/1.0.2

**Pull request merged**
